### ISSUE TITLE
Cannot find module './packages/rageserver'

### ISSUE THREAD

**Issue by lpossamai** [MarkCavalli/rageserver#103]
Hi. Sorry but it is unclear the installation instructions for me.

> 2. Put all files in your project.

Does that mean clone the repository under `C:\RAGEMP\server-files\packages`?
I.e.: `C:\RAGEMP\server-files\packages\rageserver`?

I do that, run all steps you mention and when executing `server.exe` I get the error:

```
[N] Starting network... - OK: (IPv4-only) at 127.0.0.1:22005
(node:17480) ExperimentalWarning: The ESM module loader is experimental.
Loading packages
        "rageserver" loaded
Error: Error: Cannot find module './packages/rageserver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getDirectories.forEach.src (<anonymous>:827:341)
    at Array.forEach (<anonymous>)
    at _initialize (<anonymous>:827:272)
    at <anonymous>:833:1
[P] Plugin bridge.dll loaded!
Started HTTP server at 22006 port.
```

What am I doing wrong? Thanks!

**Comment by lpossamai** [comment]
This has been fixed. I put the files under `C:\RAGEMP\server-files\`. Thanks!
