### ISSUE TITLE
Startup error.

### ISSUE THREAD

**Issue by MRCINC** [MarkCavalli/rageserver#27]
Hi, when I start the server I get an SSL error (not sure) what can be the problem and how to solve it?

```
[N] Starting network... - OK: (IPv4-only) at 127.0.0.1:22005
(node:3480) ExperimentalWarning: The ESM module loader is experimental.
Loading maps:
        "fences.xml.json" loaded
Loading packages
        "RP" loaded
[2018-08-06T11:28:20.884] [FATAL] default - Server Started
[P] Plugin bridge.dll loaded!
Started HTTP server at 22006 port.
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1036:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:637:8) code: 'ECONNECTION', command: 'CONN' }
```

**Comment by MarkCavalli** [comment]
https://stackoverflow.com/questions/47460500/node-js-http2-server-error-socket-hang-up
I think, its rage error

**Comment by MarkCavalli** [comment]
Try start clean server

**Comment by MRCINC** [comment]
Clean server is stable.
Server with a different gamemode so the same works consistently.

**Comment by MarkCavalli** [comment]
Are you use mysql server at different host? Not at localhost?

**Comment by MRCINC** [comment]
No. I use local MySQL server.

```
"use strict"

const mysql = require("mysql");
const connection =  mysql.createPool({
	host			:	"127.0.0.1",       
	user			: 	"fprpx",
	password		: 	"******",
	database		:	"fprpx",
});

connection.getConnection(function(e) {
	if (e) 	{
		log.error("DATABASE IS NOT WORKING");
		throw e;
	}
	else 	{
		log.debug(`DATABASE IS WORKING`);
	}
});

module.exports = connection;
```

**Comment by MRCINC** [comment]
Ok. Thanks.
I'll write if I find the reason. This will help development.

**Comment by MRCINC** [comment]
Hi, I commented on sMailer.js and the error is gone.
I also noticed that the logs by type "DATABASE is WORKING" are not displayed.

**Comment by MarkCavalli** [comment]
Problem is nodemailer module. Also old gmail account have some mistakes. Try to create another account.
Maybe you pasted wrong data
