### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Kalle801** [MarkCavalli/rageserver#90]
`DATABASE IS WORKING
(node:10284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of null
    at r.createBuyerEntities (C:\RAGEMP\server-files\packages\RP\index.js:1:19717)
    at new e.exports (C:\RAGEMP\server-files\packages\RP\index.js:1:19232)
    at new r (C:\RAGEMP\server-files\packages\RP\index.js:1:97419)
    at C:\RAGEMP\server-files\packages\RP\index.js:1:100446
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
EMAIL SERVER READY!`

**Comment by Kalle801** [comment]
Second error (Cars can not be purchased)

`(node:13352) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of null
    at new e.exports (C:\RAGEMP\server-files\packages\RP\index.js:1:69606)
    at Object.saveNewCar (C:\RAGEMP\server-files\packages\RP\index.js:1:43073)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`

**Comment by Kalle801** [comment]
Both messages are cause i did not fully setup the Business. Can be closed ;)
